version: '2'
services:
    web:
        build: ./docker/web/
        depends_on:
            - data
            - neo4j
        links:
            - data
            - neo4j
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
        volumes_from:
            - data
    neo4j:
        image: tpires/neo4j
        ports:
            - 7474:7474
        volumes_from:
            - data
    data:
        build: ./docker/data/
