<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/app/App.css">
    <link rel="stylesheet" href="/app/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/app/node_modules/bootstrap/dist/css/bootstrap-theme.min.css">
    <title>Six Degrees</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Six Degrees</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="https://neo4j.com/developer/cypher-query-language/" target="_blank">Help</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul id="users" class="nav nav-sidebar">
                <?php foreach ($data['users'] as $user): ?>
                    <li class="clearfix">
                        <p class="pull-left"><img class="img-circle avatar" src="<?php echo $user->getAvatar();?>" alt=""/></p>
                        <a href="" data-type="user" data-username="<?= $user->getUsername(); ?>" class="username">
                            <?php echo $user->getUsername(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="main">
            <iframe src="http://<?= $data['neo4jIframeHost'] ?>:8080/neo4j" id="neo4j" width="83%" height="100%"></iframe>
        </div>
    </div>
</div>

<script src="/app/node_modules/jquery/dist/jquery.min.js"></script>
<script src="/app/styling.js"></script>
<script src="/app/iframe-bridge.js"></script>
</body>
</html>
