<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/app/App.css">
    <link rel="stylesheet" href="/app/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/app/node_modules/bootstrap/dist/css/bootstrap-theme.min.css">
    <title>Six Degrees</title>
</head>
<body>
    <div id="root"></div>
    <script src="app/build/static/js/main.5a1bf368.js"></script>
</body>
</html>
